---
output:
  word_document:
    toc: false
    keep_md: false
    reference_docx: boot/initial/data/reportTemplate.docx
---

```{r libraries, include=FALSE}
library(knitr)
library(pander)
```

```{r chunk_setup, include=FALSE}
# CHUNK SETUPS #################################################################
knitr::opts_chunk$set(echo = FALSE, warning = FALSE,
                      message=FALSE, results = 'asis')
```

```{r pander_settings, include = FALSE}
# PANDER OPTIONS ##############################################################
panderOptions('table.split.table', Inf)
panderOptions('keep.trailing.zeros', FALSE)
panderOptions('table.alignment.default', "center")
```


```{r aquaculture-allRegions-BLT}
risk_table <- read.taf("report/2025_aquaculture-allRegions-BLT.csv")

# set caption
set.caption("Table 1: Risk assessment for aquaculture in the BLT region")

# Output table
#pander(style_table1(catch_table), missing = "-")
pander(risk_table, missing = "-")
```

```{r aquaculture-allRegions-MED}
risk_table <- read.taf("report/2025_aquaculture-allRegions-MED.csv")

# set caption
set.caption("Table 2: Risk assessment for aquaculture in the MED region")

# Output table
#pander(style_table1(catch_table), missing = "-")
pander(risk_table, missing = "-")
```

```{r aquaculture-allRegions-NEA}
risk_table <- read.taf("report/2025_aquaculture-allRegions-NEA.csv")

# set caption
set.caption("Table 3: Risk assessment for aquaculture in the NEA region")

# Output table
#pander(style_table1(catch_table), missing = "-")
pander(risk_table, missing = "-")
```

```{r aquaculture-lowTrophic-ADR}
risk_table <- read.taf("report/2025_aquaculture-lowTrophic-ADR.csv")

# set caption
set.caption("Table 4: Risk assessment for aquaculture in the ADR region")

# Output table
#pander(style_table1(catch_table), missing = "-")
pander(risk_table, missing = "-")
```

```{r aquaculture-lowTrophic-GNS}
risk_table <- read.taf("report/2025_aquaculture-lowTrophic-GNS.csv")

# set caption
set.caption("Table 5: Risk assessment for aquaculture in the GNS region")

# Output table
#pander(style_table1(catch_table), missing = "-")
pander(risk_table, missing = "-")
```


```{r ADR-fisheries}
risk_table <- read.taf("report/2025_fisheries-ADR.csv")

# set caption
set.caption("Table 6: Risk assessment for fisheries in the ADR region")

# Output table
#pander(style_table1(catch_table), missing = "-")
pander(risk_table, missing = "-")
```

```{r BLT-N-fisheries}
risk_table <- read.taf("report/2025_fisheries-BLT-N.csv")

# set caption
set.caption("Table 7: Risk assessment for fisheries in the BLT-N region")

# Output table
#pander(style_table1(catch_table), missing = "-")
pander(risk_table, missing = "-")
```

```{r BLT-S-fisheries}
risk_table <- read.taf("report/2025_fisheries-BLT-S.csv")

# set caption
set.caption("Table 8: Risk assessment for fisheries in the BLT-S region")

# Output table
#pander(style_table1(catch_table), missing = "-")
pander(risk_table, missing = "-")
```

```{r GNS-fisheries}
risk_table <- read.taf("report/2025_fisheries-GNS.csv")

# set caption
set.caption("Table 9: Risk assessment for fisheries in the GNS region")

# Output table
#pander(style_table1(catch_table), missing = "-")
pander(risk_table, missing = "-")
```

```{r MED-fisheries}
risk_table <- read.taf("report/2025_fisheries-MED.csv")

# set caption
set.caption("Table 10: Risk assessment for fisheries in the MED region")

# Output table
#pander(style_table1(catch_table), missing = "-")
pander(risk_table, missing = "-")
```

```{r ONA-fisheries}
risk_table <- read.taf("report/2025_fisheries-ONA.csv")

# set caption
set.caption("Table 11: Risk assessment for fisheries in the ONA region")

# Output table
#pander(style_table1(catch_table), missing = "-")
pander(risk_table, missing = "-")
```


```{r SoS-fisheries}
risk_table <- read.taf("report/2025_fisheries-SoS.csv")

# set caption
set.caption("Table 12: Risk assessment for fisheries in the SoS region")

# Output table
#pander(style_table1(catch_table), missing = "-")
pander(risk_table, missing = "-")
```

